services:
  db:
    image: postgres:13
    container_name: postgres_db
    env_file:
      - .env
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgresrai"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    image: krutsvitya/rai_test:latest
    container_name: fastapi_app
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: